name: 'ZeuZ Actions - Upload attachment'
description: 'Uploads attachment to ZeuZ server'
branding:
  icon: 'upload-cloud'
  color: 'red'
inputs:
  zeuz_server_host:
    description: 'host address of the zeuz server'
    required: true
  zeuz_api_key:
    description: 'api key to authenticate to zeuz'
    required: true
  zeuz_attachment_type:
    description: 'type of attachment, possible values: global, test_case, step'
    required: true
  zeuz_attachment_item_id:
    description: 'if test_case/step is selected as type, you must provide the id of the test case or step'
    required: false
    default: none
  zeuz_attachment_path:
    description: 'path to the attachment to upload attachment'
    required: true
  zeuz_attachment_replace:
    description: 'set true to replace existing attachment in place, otherwise false (default: true)'
    required: true
    default: true
outputs:
  upload_success: # output will be available to future steps
    description: 'Whether the upload was successful or not. Possible values: true, false'
runs:
  using: 'node16'
  main: 'dist/index.js'
