name: "Test action"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  test-upload-attachment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Test output
        run: echo "Hello World" >> test.txt

      - uses: sazid/zeuz-actions-upload-attachment@v1.0
        with:
          zeuz_server_host: ${{ secrets.ZEUZ_SERVER_HOST }}
          zeuz_api_key: ${{ secrets.ZEUZ_API_KEY }}
          zeuz_attachment_type: ${{ vars.ZEUZ_ATTACHMENT_TYPE }}
          zeuz_attachment_item_id: ${{ vars.ZEUZ_ATTACHMENT_ITEM_ID }}
          zeuz_attachment_path: test.txt
          zeuz_attachment_replace: true
